# Use an existing docker image as a base
FROM node:14-alpine3.17

WORKDIR /var/app/

COPY ./package*.json ./

# Download and install a dependency
RUN npm install

COPY . .

# Tell the image what to do when it starts as a container.
CMD ["node", "index.js"]